version: '3.8'

services:
  imu_publisher:
    build: .
    container_name: ros2_imu_publisher
    privileged: true
    devices:
      - "/dev/i2c-1:/dev/i2c-1"  # Adjust based on your I2C device
    environment:
      - ROS_DOMAIN_ID=0
    network_mode: host
    restart: unless-stopped
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        source /ros2_ws/install/setup.bash &&
        ros2 launch imu_mpu6050 imu_launch.py
      "
    volumes:
      - ./config:/ros2_ws/src/imu_mpu6050/config:rw  # Mount config for runtime parameter changes
